const FRASES_DEL_ANO = [
  "El hogar se construye con palabras amables y silencios oportunos.",
  "Mejor es lo poco con justicia, que la muchedumbre de frutos sin derecho. (Proverbios 16:8)",
  "La paciencia es el cimiento sobre el que se levanta toda familia firme.",
  "Mujer virtuosa, ¿quién la hallará? Porque su estima sobrepasa largamente a la de las piedras preciosas. (Proverbios 31:10)",
  "Cada gesto pequeño en casa es una semilla de algo grande mañana.",
  "El amor verdadero no busca lo suyo, se goza con la verdad. (1 Corintios 13)",
  "Un hogar feliz no es el que tiene todo, sino el que sabe agradecer lo que tiene.",
  "La sabiduría edifica su casa con paciencia y discernimiento.",
  "Honra a tu padre y a tu madre. (Éxodo 20:12)",
  "El silencio en el hogar también enseña, también sana, también edifica.",
  "Una mujer que teme a Dios, ésa será alabada. (Proverbios 31:30)",
  "Las pequeñas decisiones diarias construyen el carácter de toda una familia.",
  "El que ama, perdona; el que perdona, libera; el que libera, también es libre.",
  "Donde hay comunión, hay fortaleza; donde hay diálogo, hay paz.",
  "Sobre toda cosa guardada, guarda tu corazón, porque de él mana la vida. (Proverbios 4:23)",
  "El verdadero líder del hogar sirve antes que mandar.",
  "Las manos que trabajan en silencio sostienen los hogares más firmes.",
  "Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios. (Mateo 5:9)",
  "La gratitud convierte lo poco en suficiente y lo cotidiano en sagrado.",
  "Una mujer sabia edifica su casa; mas la necia con sus manos la derriba. (Proverbios 14:1)",
  "El respeto se cultiva en cada palabra que decidimos no decir cuando estamos heridos.",
  "El hogar es el primer lugar donde aprendemos quiénes somos.",
  "El amor cubre multitud de faltas. (1 Pedro 4:8)",
  "Servir a quienes amamos no es debilidad, es la forma más alta de fortaleza.",
  "Honra a tu esposa como a vaso más frágil, y heredarás bendición. (1 Pedro 3:7)",
  "La constancia silenciosa supera al esfuerzo brillante pero pasajero.",
  "En las pequeñas cosas se nota la grandeza del que ama de verdad.",
  "Hijos son herencia de Jehová; cosa de estima el fruto del vientre. (Salmo 127:3)",
  "El que ahorra hoy se da libertad mañana.",
  "Un hogar es la suma de los detalles que se cuidan cuando nadie está mirando.",
  "Más vale un bocado seco con paz, que casa de contiendas llena de provisiones. (Proverbios 17:1)",
  "La humildad escucha; el orgullo solo espera su turno para hablar.",
  "Las palabras de la mujer sabia son ley de clemencia en su lengua. (Proverbios 31:26)",
  "Quien administra bien lo poco, recibirá la confianza de mucho.",
  "El amor es paciente, es benigno, no tiene envidia. (1 Corintios 13:4)",
  "Cada día sin reproche es una piedra más en el muro del hogar.",
  "La oración compartida es el lazo invisible que sostiene la casa.",
  "Una mujer fuerte no es la que nunca cae, sino la que se levanta con fe.",
  "El dinero es siervo de quien sabe gobernarlo, y amo de quien lo idolatra.",
  "Encomienda a Jehová tus obras, y tus pensamientos serán afirmados. (Proverbios 16:3)",
  "El hogar se cuida como se cuida un jardín: con presencia diaria.",
  "El que escucha bien, ama bien.",
  "Bendita es la mujer que extiende su mano al pobre. (Proverbios 31:20)",
  "Hablar menos y observar más es la disciplina de los hogares sabios.",
  "La fidelidad cotidiana vale más que el romanticismo del momento.",
  "El que da con alegría, recibe con paz. (2 Corintios 9:7)",
  "Los hijos imitan lo que ven, no lo que oyen.",
  "Las palabras suaves quitan la ira; las ásperas hacen subir el furor. (Proverbios 15:1)",
  "Toda casa que se cuida con amor se vuelve refugio para los demás.",
  "El esposo que ama edifica; el que critica, demuele.",
  "La mujer agraciada tendrá honra. (Proverbios 11:16)",
  "Las metas compartidas unen más que los gustos en común.",
  "La paz del hogar empieza en el silencio interior de cada uno.",
  "Buscad primeramente el reino de Dios y su justicia. (Mateo 6:33)",
  "Quien controla sus impulsos, gobierna su casa.",
  "El cariño expresado a tiempo evita heridas que no sanan.",
  "Vivamos sobriamente, justa y piadosamente en este siglo. (Tito 2:12)",
  "Lo que ahorramos hoy son las decisiones libres que tomaremos mañana.",
  "Una caricia oportuna vale más que mil discursos.",
  "Su marido es conocido en las puertas, cuando se sienta con los ancianos. (Proverbios 31:23)",
  "El verdadero éxito empieza dentro de las paredes de tu casa.",
  "Quien se esfuerza por su familia jamás siembra en vano.",
  "Mejor es el fin del negocio que su principio. (Eclesiastés 7:8)",
  "El orden externo nace del orden interno.",
  "Hablar bien del cónyuge frente a otros fortalece el lazo.",
  "Casas y riquezas son herencia de los padres; mas de Jehová la mujer prudente. (Proverbios 19:14)",
  "El que se domina a sí mismo, gobierna mejor que el que conquista ciudades.",
  "Las raíces invisibles sostienen al árbol que todos admiran.",
  "Dad, y se os dará. (Lucas 6:38)",
  "Una palabra de aliento puede cambiar el rumbo de toda una semana.",
  "El esposo que escucha de verdad ya está amando.",
  "Pasajera es la gracia, y vana la hermosura; la mujer que teme a Jehová, ésa será alabada. (Proverbios 31:30)",
  "El hogar próspero no es el más rico, sino el más unido.",
  "La generosidad enseña más que mil sermones.",
  "Si dos no estuvieren de acuerdo, ¿andarán juntos? (Amós 3:3)",
  "El que reconoce su error gana respeto; el que lo niega, lo pierde.",
  "La oración del esposo y la esposa es como dos manos que sostienen una sola luz.",
  "El amor todo lo sufre, todo lo cree, todo lo espera. (1 Corintios 13:7)",
  "Los detalles diarios son las pinceladas con las que se pinta el matrimonio.",
  "Una casa donde se ríe es una casa donde se sana.",
  "El temor de Jehová es el principio de la sabiduría. (Proverbios 9:10)",
  "El esposo sabio guía con presencia, no con presión.",
  "El silencio compartido es signo de confianza profunda.",
  "Nada hagáis por contienda o por vanagloria. (Filipenses 2:3)",
  "Lo que se siembra en familia se cosecha en futuras generaciones.",
  "Ser mujer fuerte es elegir la ternura cuando todos esperan dureza.",
  "El que halla esposa halla el bien, y alcanza la benevolencia de Jehová. (Proverbios 18:22)",
  "El presupuesto cuidado es un acto de amor invisible.",
  "Cada gesto de servicio en el hogar es un pequeño acto de fe.",
  "No os afanéis por el día de mañana. (Mateo 6:34)",
  "Una sonrisa al llegar a casa cura más que cualquier remedio.",
  "El amor maduro no se mide en intensidad, sino en constancia.",
  "Cuando dos se ponen de acuerdo, hasta la pobreza se vuelve abundancia.",
  "Andad como hijos de luz. (Efesios 5:8)",
  "El hogar es la primera escuela de gratitud.",
  "Una madre que ora silenciosamente protege más que mil muros.",
  "El que es fiel en lo muy poco, también en lo más es fiel. (Lucas 16:10)",
  "Las heridas del hogar se sanan con humildad, no con razón.",
  "El que da gracias por lo poco recibe la abundancia.",
  "Mira a la ropa, sus criados están bien vestidos. (Proverbios 31:21)",
  "Más se construye con un sí firme que con cien quizás.",
  "Cada decisión financiera es un voto sobre el futuro de la familia.",
  "Levántate, resplandece. (Isaías 60:1)",
  "El hogar es el espejo más honesto de quiénes somos.",
  "La intimidad nace donde hay verdad sin máscara.",
  "Por encima de todo, amaos los unos a los otros. (1 Pedro 4:8)",
  "Un hombre se prueba en cómo trata a su esposa cuando nadie los ve.",
  "Las cuentas claras hacen las amistades duraderas, también dentro del matrimonio.",
  "La ley de la clemencia está en su lengua. (Proverbios 31:26)",
  "El perdón no borra el pasado, pero abre futuro.",
  "Las pequeñas victorias diarias se suman a una vida virtuosa.",
  "Bienaventurados los limpios de corazón, porque ellos verán a Dios. (Mateo 5:8)",
  "Quien ama a su familia, primero se cuida a sí mismo.",
  "El hogar no es perfecto; es el lugar donde aprendemos a perfeccionar el amor.",
  "Y todo lo que hagáis, hacedlo de corazón, como para el Señor. (Colosenses 3:23)",
  "La constancia es el lenguaje secreto del amor maduro.",
  "Una palabra a tiempo es como manzana de oro con figuras de plata. (Proverbios 25:11)",
  "Los hijos no necesitan padres perfectos, necesitan padres presentes.",
  "El esposo que cuida sus palabras protege el corazón de su esposa.",
  "El gozo del Señor es vuestra fuerza. (Nehemías 8:10)",
  "El hogar feliz se planea como se planea una huerta: con paciencia.",
  "La mujer que confía en Dios irradia paz a quienes la rodean.",
  "Plantó viña; ciñó de fuerza sus lomos. (Proverbios 31:16-17)",
  "El verdadero proveedor no solo trae dinero, trae paz.",
  "Cada peso ahorrado es una palabra que dice: pienso en ti.",
  "Confía en Jehová con todo tu corazón, y no te apoyes en tu propia prudencia. (Proverbios 3:5)",
  "Los hijos imitan el tono con que sus padres se hablan.",
  "Dar tiempo es dar lo más valioso que tenemos.",
  "Una mujer prudente edifica con palabras lo que las manos no alcanzan.",
  "Sed agradecidos. (Colosenses 3:15)",
  "El amor pequeño y constante vence al amor grande y pasajero.",
  "Quien se sienta a comer con su familia siembra recuerdos.",
  "Buscad la paz, y seguidla. (1 Pedro 3:11)",
  "Cuando el hombre cuida lo doméstico, multiplica su autoridad.",
  "Las decisiones difíciles se toman mejor en pareja que en soledad.",
  "Su lámpara no se apaga de noche. (Proverbios 31:18)",
  "El descanso compartido es tan importante como el trabajo compartido.",
  "Cada error perdonado es un cimiento más en la casa.",
  "Vístase de fortaleza y honor. (Proverbios 31:25)",
  "El amor verdadero se nota más en los días grises que en los soleados.",
  "Una familia sin metas comunes es un barco sin timón.",
  "Esfuérzate y sé valiente. (Josué 1:9)",
  "El cuidado del cuerpo, del alma y del bolsillo son hermanos en el hogar.",
  "Las palabras dulces a tiempo construyen más que mil regalos costosos.",
  "Levanta sus hijos y la llaman bienaventurada. (Proverbios 31:28)",
  "La mujer que se conoce a sí misma fortalece a toda su casa.",
  "El verdadero amor no se calla las cosas importantes, las dice con cuidado.",
  "Cantad alegres a Dios. (Salmo 100:1)",
  "Reír juntos es un escudo contra los problemas.",
  "El que sabe escuchar entiende lo que las palabras no dicen.",
  "Estad siempre gozosos, orad sin cesar, dad gracias en todo. (1 Tesalonicenses 5:16-18)",
  "La ternura es la valentía de los fuertes.",
  "Un hombre que abraza a su esposa todos los días sostiene la casa entera.",
  "Hace telas, y vende; y da cintas al mercader. (Proverbios 31:24)",
  "El dinero gastado con propósito construye; gastado sin pensar, destruye.",
  "Cuando uno calla por amor, el otro habla con más cuidado.",
  "Os volveré como la tierra de promisión. (Ezequiel 36:11)",
  "El hogar próspero es el que reparte tareas sin rencores.",
  "La humildad en pareja es saber decir: tienes razón.",
  "Más vale ir a la casa del luto que a la casa del banquete. (Eclesiastés 7:2)",
  "Los problemas compartidos pesan la mitad; las alegrías compartidas pesan el doble.",
  "Una mujer en oración cambia el clima de todo un hogar.",
  "Su semilla será poderosa en la tierra. (Salmo 112:2)",
  "El mejor legado no es el dinero, son los valores transmitidos.",
  "Cuando dos personas se eligen cada día, el matrimonio florece.",
  "Mejor es la paciencia que la altivez de espíritu. (Eclesiastés 7:8)",
  "Los gestos sencillos son los que dejan huellas profundas.",
  "Cuidar las finanzas también es cuidar el matrimonio.",
  "No os conforméis a este siglo, sino transformaos por la renovación de vuestro entendimiento. (Romanos 12:2)",
  "El hogar que ora junto, permanece junto.",
  "La mujer sabia conoce el momento de hablar y el momento de callar.",
  "Quien anhela tener antes que ser, perderá ambos. (Proverbios 13:11)",
  "El verdadero hombre no es el que jamás llora, es el que jamás abandona.",
  "Una palabra escrita con amor puede sanar lo que mil discursos no logran.",
  "El que es lento para la ira es grande de entendimiento. (Proverbios 14:29)",
  "Los hijos que ven amor entre sus padres aprenden el amor sin libros.",
  "El tiempo de calidad no se programa, se prioriza.",
  "Bienaventurado todo aquel que teme a Jehová, que anda en sus caminos. (Salmo 128:1)",
  "Una pareja que se respeta jamás se grita en público.",
  "El presupuesto familiar es un mapa hacia los sueños compartidos.",
  "Y hace que tu mujer sea como vid que lleva fruto a los lados de tu casa. (Salmo 128:3)",
  "El esposo que celebra los pequeños logros de su esposa la enaltece.",
  "Lo que se da con amor jamás se pierde.",
  "El que es bueno alcanzará favor de Jehová. (Proverbios 12:2)",
  "Las casas más fuertes son las que se han reparado muchas veces.",
  "Ser fiel en los detalles es el más alto grado de amor.",
  "Buscad las cosas de arriba. (Colosenses 3:1)",
  "Cuando el corazón está en paz, la casa entera respira mejor.",
  "Una familia es un pequeño país con sus propias leyes de amor.",
  "Más vale lo poco bien hecho que lo mucho hecho a medias.",
  "Mas el justo está confiado como un león. (Proverbios 28:1)",
  "El esposo que ora por su esposa la cubre de bendición.",
  "Las disciplinas pequeñas hacen los grandes hogares.",
  "Camina en el camino de los buenos. (Proverbios 2:20)",
  "La autenticidad en el hogar es más valiosa que la perfección.",
  "Quien planifica sus gastos respeta a quienes ama.",
  "Y todo lo que pidiereis al Padre en mi nombre, lo haré. (Juan 14:13)",
  "El hogar feliz no se hereda, se construye día a día.",
  "Una mujer que se cuida a sí misma puede cuidar mejor a los demás.",
  "Se levanta aún de noche, y da comida a su familia. (Proverbios 31:15)",
  "Las grandes decisiones se piensan con la mente y se sienten con el corazón.",
  "Decir te amo importa, pero demostrarlo importa más.",
  "Y sobre todas estas cosas vestíos de amor. (Colosenses 3:14)",
  "El que cuida lo material también cuida lo espiritual de su familia.",
  "Una pareja unida ante las adversidades es más fuerte que cualquier muro.",
  "El que llega tarde por servir, nunca llega tarde de verdad.",
  "Como aretes de oro y joyas de oro fino es el que reprende al sabio que tiene oído dócil. (Proverbios 25:12)",
  "Las palabras de bendición pronunciadas en casa moldean el destino.",
  "El verdadero patrimonio familiar son los recuerdos creados con presencia.",
  "Pon orden en tu casa, porque morirás. (Isaías 38:1) — vivir con propósito.",
  "Una madre cansada que ora supera a un guerrero descansado.",
  "El equilibrio entre dar y recibir es el secreto del matrimonio sano.",
  "Y el rey amó a Ester sobre todas las otras mujeres. (Ester 2:17)",
  "Cuando el esposo eleva a su esposa, se eleva a sí mismo.",
  "Cada peso que decidimos no gastar es un voto por nuestra paz futura.",
  "Aún no os habéis resistido hasta la sangre, combatiendo contra el pecado. (Hebreos 12:4)",
  "El hogar floreciente nace de pequeños hábitos repetidos con fe.",
  "Una conversación honesta vale más que mil silencios incómodos.",
  "Por cuanto fuiste fiel en lo poco, sobre mucho te pondré. (Mateo 25:21)",
  "Servir a la pareja con alegría es la forma más alta de oración cotidiana.",
  "Los sueños grandes se construyen con disciplinas pequeñas.",
  "El amor es el cumplimiento de la ley. (Romanos 13:10)",
  "Una familia es un equipo que juega para ganar la vida juntos.",
  "Cuidar el dinero es cuidar el tiempo que tomó ganarlo.",
  "El consejo de los justos es rectitud. (Proverbios 12:5)",
  "El esposo que admite no saber, está más cerca de la sabiduría.",
  "El detalle inesperado conmueve más que el regalo planeado.",
  "El gozo del corazón hermosea el rostro. (Proverbios 15:13)",
  "Los hijos no recuerdan cuánto tuvieron, recuerdan cuánto los amaron.",
  "Una casa sin gritos no es una casa sin problemas, es una casa con dominio propio.",
  "El que es benigno será bendecido, porque dio de su pan al menesteroso. (Proverbios 22:9)",
  "Lo que llaman suerte, los hogares ordenados lo llaman costumbre.",
  "El amor maduro se mide en años de paciencia, no en chispas de pasión.",
  "Reconócelo en todos tus caminos, y él enderezará tus veredas. (Proverbios 3:6)",
  "Una mujer firme y dulce es columna invisible del hogar.",
  "El descanso del séptimo día protege la productividad de los otros seis.",
  "Acordaos del día de reposo para santificarlo. (Éxodo 20:8)",
  "Cuando el esposo y la esposa rezan juntos, el enemigo huye.",
  "El presupuesto es una herramienta de libertad, no de cárcel.",
  "Si Jehová no edificare la casa, en vano trabajan los que la edifican. (Salmo 127:1)",
  "Los pequeños actos de bondad diaria construyen catedrales de amor.",
  "Hablar bien de los hijos delante de los demás los fortalece.",
  "El que retiene el castigo, a su hijo aborrece. (Proverbios 13:24)",
  "Un padre presente es mejor que un padre famoso.",
  "Las heridas más profundas suelen sanar con las palabras más sencillas.",
  "Antes que el quebrantamiento es la soberbia. (Proverbios 16:18)",
  "El verdadero líder espiritual del hogar lava los pies, no los pisa.",
  "Una conversación pendiente es como un techo con goteras: tarde o temprano cede.",
  "Y considerémonos unos a otros para estimularnos al amor y a las buenas obras. (Hebreos 10:24)",
  "Ahorrar no es no disfrutar; es disfrutar también del futuro.",
  "Una mujer en paz contagia paz a toda su familia.",
  "Mira los lirios del campo. (Mateo 6:28)",
  "El que comparte su vida está siempre acompañado.",
  "Las grandes familias se construyen con miles de gestos olvidables.",
  "El justo florecerá como la palmera. (Salmo 92:12)",
  "Quien cumple su palabra dentro del hogar, gana respeto fuera de él.",
  "Una madre amada por su esposo cría hijos seguros.",
  "Y todo lo que hiciereis, sea con amor. (1 Corintios 16:14)",
  "El esposo agradecido enciende el hogar como una lámpara.",
  "Los sueños pagados al contado son los más dulces de disfrutar.",
  "Sé tú mi roca de refugio. (Salmo 71:3)",
  "Las raíces familiares fuertes producen ramas valientes.",
  "El hogar acogedor no depende del tamaño de la casa, sino del tamaño del corazón.",
  "Como el padre se compadece de los hijos, se compadece Jehová de los que le temen. (Salmo 103:13)",
  "Una familia que perdona pronto, sufre poco.",
  "El verdadero amor construye, no controla.",
  "Sin consulta los pensamientos son frustrados; mas en la multitud de consejeros se afirman. (Proverbios 15:22)",
  "Los hábitos del hogar se vuelven el carácter de los hijos.",
  "Decir gracias en casa es tan importante como decirlo en la calle.",
  "Honra a todos. Amad a los hermanos. Temed a Dios. (1 Pedro 2:17)",
  "Cuando uno cede por amor, ambos ganan.",
  "Las metas financieras compartidas unen como pocas cosas en el matrimonio.",
  "Levantaos a los caídos. (Isaías 35:3)",
  "Una mujer sostenida por la fe es inquebrantable.",
  "El esposo que llega a casa con paz, contagia paz.",
  "Mas yo y mi casa serviremos a Jehová. (Josué 24:15)",
  "Cuidar el cuerpo en pareja es una manera silenciosa de decir te quiero por años.",
  "Cada gasto es una pequeña confesión de nuestras prioridades.",
  "Buscad y hallaréis. (Mateo 7:7)",
  "Las grandes familias no son las que nunca discuten, son las que saben reconciliarse.",
  "Un día sin reproches es una pequeña victoria del amor.",
  "Echa tu pan sobre las aguas. (Eclesiastés 11:1)",
  "El esposo que cocina ocasionalmente para su esposa la sorprende dos veces.",
  "Una buena administración del hogar es signo de respeto profundo.",
  "Vestíos del Señor Jesucristo. (Romanos 13:14)",
  "Cuando hablamos bien del cónyuge en su ausencia, lo amamos en presencia.",
  "Las metas pequeñas alcanzadas crean confianza para metas grandes.",
  "El justo come hasta saciar su alma. (Proverbios 13:25)",
  "El hogar que comparte la mesa comparte la vida.",
  "Una mujer descansada es una bendición para toda su casa.",
  "Y descansaron en el día de reposo. (Lucas 23:56)",
  "Trabajar duro es honorable, pero saber descansar también lo es.",
  "Las pequeñas economías diarias se convierten en grandes libertades.",
  "Por cuanto pusiste tus ojos en el santo, te he librado. (Salmo 91:14)",
  "Quien escucha sin interrumpir está practicando un acto sagrado.",
  "El servicio mutuo en el matrimonio es el mejor antídoto contra la rutina.",
  "Mas tú, hijo de hombre, oye lo que yo te hablo. (Ezequiel 2:8)",
  "Los matrimonios fuertes no son los que nunca tienen tormentas, son los que aprendieron a navegar juntos.",
  "Hablar bien del padre o la madre delante de los hijos los honra a todos.",
  "Tres cosas me son ocultas; aun tampoco sé la cuarta. (Proverbios 30:18) — humildad ante el misterio del amor.",
  "El presupuesto familiar bien planeado da paz mental a ambos.",
  "Una familia que viaja unida no necesita lugares lejanos para ser feliz.",
  "Levanta tus ojos a los montes, de donde vendrá mi socorro. (Salmo 121:1)",
  "Quien busca culpables nunca encuentra soluciones.",
  "Una palabra de fe en el desayuno cambia todo el día.",
  "El amor de muchos se enfriará. (Mateo 24:12) — protege el tuyo.",
  "Las decisiones se discuten antes; la unidad se muestra después.",
  "Quien cuida el matrimonio cuida la primera escuela de los hijos.",
  "El que ama disciplina temprano. (Proverbios 13:24)",
  "Una mujer creativa transforma cualquier espacio en un hogar.",
  "Las pequeñas tradiciones familiares son los cimientos de la identidad.",
  "Y todo lo que hagáis, hacedlo todo para la gloria de Dios. (1 Corintios 10:31)",
  "El esposo que pide perdón rápido sana heridas profundas.",
  "Una casa donde se canta es una casa donde la fe vive.",
  "Cantad a Jehová cántico nuevo. (Salmo 96:1)",
  "El amor verdadero se nota en cómo se trata al cónyuge cansado.",
  "El ahorro es paciencia con forma de monedas.",
  "Los que esperan en Jehová tendrán nuevas fuerzas. (Isaías 40:31)",
  "Un hogar fuerte es un refugio en un mundo agitado.",
  "Las palabras de bendición pronunciadas con fe se hacen realidad con el tiempo.",
  "Y a la mujer dijo: Multiplicaré en gran manera tus dolores. (Génesis 3:16) — y aún así, ella levanta el mundo.",
  "Cuando el esposo aplaude los logros de la esposa, ella florece.",
  "Una crisis bien manejada en pareja une más que mil días buenos.",
  "Toda la Escritura es inspirada por Dios, y útil. (2 Timoteo 3:16)",
  "El que enseña con el ejemplo no necesita gritar para ser oído.",
  "Las decisiones financieras tomadas en frío son siempre mejores que las tomadas en caliente.",
  "Mejor es la sabiduría que las piedras preciosas. (Proverbios 8:11)",
  "Una madre orante es la guardiana invisible de toda la familia.",
  "El gesto de prepararle algo a la pareja es lenguaje del alma.",
  "Y conoceréis la verdad, y la verdad os hará libres. (Juan 8:32)",
  "El hogar bien gobernado se nota en los detalles de los hijos.",
  "Quien comparte sus sueños con su pareja los hace más posibles.",
  "Cuando hicieres voto a Jehová, no tardes en pagarlo. (Deuteronomio 23:21)",
  "El compromiso es el esqueleto invisible del amor maduro.",
  "Una decisión postergada en pareja es una decisión que se debilita.",
  "El necio toma a mal el consejo de su padre. (Proverbios 15:5)",
  "Hablar con voz baja en momentos tensos es la disciplina del amor.",
  "Las grandes familias se notan en los detalles que nadie ve.",
  "Tu palabra es lámpara a mis pies, y lumbrera a mi camino. (Salmo 119:105)",
  "El descanso del esposo y la esposa es tan sagrado como su trabajo.",
  "Una familia que celebra los pequeños logros nunca pierde el rumbo.",
  "El día final del año: que la sabiduría que recogimos hoy sea la siembra de mañana.",
  "Esfuérzate y sé valiente; no temas ni desmayes. (Deuteronomio 31:6)",
  "El que cuida lo pequeño en casa, recibe la confianza para lo grande.",
  "Una pareja que ríe junta envejece junta.",
  "El amor maduro es decisión sostenida, no emoción pasajera.",
  "Mejor es la respuesta blanda que la palabra que enciende la ira. (Proverbios 15:1)",
  "Quien protege la dignidad de su esposa se protege a sí mismo.",
  "Las cuentas del hogar son un acto de transparencia y confianza.",
  "Cantad a Jehová bendiciendo su nombre. (Salmo 96:2)",
  "Una tarde tranquila en familia es más rica que una fiesta vacía.",
  "El que escucha con paciencia descubre lo que las palabras esconden.",
  "Bienaventurados los misericordiosos, porque ellos alcanzarán misericordia. (Mateo 5:7)",
  "El esposo presente vale más que mil regalos enviados desde lejos.",
  "Una casa ordenada calma la mente de quienes la habitan.",
  "El que es sabio teme y se aparta del mal. (Proverbios 14:16)",
  "La fidelidad cotidiana es la moneda más valiosa del matrimonio.",
  "Una mujer descansada en Dios irradia fuerza silenciosa.",
  "Buscad a Jehová mientras puede ser hallado. (Isaías 55:6)",
  "Los hijos heredan más de lo que ven que de lo que oyen.",
  "Cada compra meditada es una pequeña victoria sobre el impulso.",
  "Y vendrá sobre ti toda esta bendición. (Deuteronomio 28:2)",
  "El esposo que escucha con atención abraza con palabras.",
  "El hogar es el lugar donde se aprende a perdonarse a uno mismo.",
  "Y mi pueblo habitará en morada de paz. (Isaías 32:18)",
  "Que cada amanecer sea una oportunidad nueva de edificar el hogar."
];

if (typeof module !== 'undefined' && module.exports) module.exports = FRASES_DEL_ANO;
